#!/bin/bash

#TODO - eyewitness, naabu, nuclei

trap ctrl_c INT

function ctrl_c() {
        printf '\nBye!\n'
        rm out1 out2 out3 subs1 subs2 subs3 allsubs take1 take2 results
        exit 1
} 2>/dev/null

if [ -z $1 ]
then
        echo 'Usage: subinfo <domain>'
        exit 1
fi

### SUBDOMAIN ENUM ###

echo '[*] Enumerating subdomains...'

subfinder -timeout 10 -silent -d $1 > out1
cat out1 >> subs1

assetfinder -subs-only $1 > out2
cat out2 >> subs2

amass enum -silent -nolocaldb -passive -d $1 -o out3 &> /dev/null
cat out3 >> subs3

rm out1 out2 out3

sort -u subs1 subs2 subs3 > allsubs
rm subs1 subs2 subs3

### HOST DISCOVERY ###

echo '[*] Identifying live hosts...'

live=$(echo live-hosts-$1)
cat allsubs | httprobe > $live

### S3 BUCKETS ###

echo '[*] Finding S3 buckets...'

s3scanner allsubs 2>&1 | grep -F [found] > s3
rm buckets.txt

if [ -s s3 ]
then
        cat s3
        rm s3
else
        rm s3
fi

### SUBDOMAIN TAKEOVER ###

echo '[*] Testing for subdomain takeover...'

subjack -w allsubs -timeout 5 -t 20 -a -o take1 &> /dev/null
subjack -w allsubs -timeout 5 -t 20 -a -ssl -o take2 &> /dev/null

if [ -s take1 ] && [ -s take2 ]
then
	sort -u take1 take2 > results
	cat results
	rm take1 take2 results
elif [ -s take1 ]
then
	cat take1
	rm take1
elif [ -s take2 ]
then
	cat take2
	rm take2
fi

### FAVICON RECON ###

echo '[*] Performing favicon recon...'
cat $live | favfreak.py | sed -n '/FingerPrint/,/Summary/p' | head -n -4 | tail -n +3 > fav

if [ -s fav ]
then
	cat fav
	rm fav
else
	rm fav
fi

rm allsubs
echo '[*] Done.'
