#!/bin/bash

#TODO: gowitness help, options

trap ctrl_c INT

function ctrl_c() {
        printf '\nBye!\n'
	cd ..
	rm -r $temp $results
        exit 1
} 2>/dev/null

if [ -z $1 ]
then
        echo 'Usage: subinfo <domain>'
        exit 1
fi

temp=$(echo temp-$1)
results=$(echo results-$1)
rm -r $temp $results 2>/dev/null
mkdir $temp $results

cd $temp

### SUBDOMAIN ENUM ###

echo '[*] Enumerating subdomains...'

subfinder -timeout 5 -t 20 -silent -d $1 -o out1 &> /dev/null
cat out1 >> subs1

assetfinder -subs-only $1 > out2
cat out2 >> subs2

amass enum -silent -nolocaldb -passive -d $1 -o out3 &> /dev/null
cat out3 >> subs3

sort -u subs1 subs2 subs3 > allsubs

### HOST DISCOVERY ###

echo '[*] Identifying live hosts...'

echo '*** LIVE HOSTS ***' >> ../$results/all-results
echo '' >> ../$results/all-results

cat allsubs | httprobe -prefer-https -t 5000 -c 40 > ../$results/live-hosts

echo "Found `wc -l ../$results/live-hosts | cut -f1 -d ' '` live hosts" >> ../$results/all-results

### ADDITIONAL PORTS ###

echo '[*] Checking additional ports...'

echo '' >> ../$results/all-results
echo '*** ADDITIONAL PORTS ***' >> ../$results/all-results
echo '' >> ../$results/all-results

naabu -l allsubs -p 21,22,23,139,445,1433,3306,3389,8000,8080,8443,10000 -rate 100 -silent >> ../$results/all-results

### S3 BUCKETS ###

echo '[*] Finding S3 buckets...'

s3scanner scan -f allsubs | grep -v http | grep bucket_exists > s3

echo '' >> ../$results/all-results
echo '*** S3 BUCKETS ***' >> ../$results/all-results
echo '' >> ../$results/all-results

if [ -s s3 ]
then
        cat s3 >> ../$results/all-results
fi

### SUBDOMAIN TAKEOVER ###

echo '[*] Testing for subdomain takeover...'

subjack -w allsubs -timeout 5 -t 20 -a -ssl -o take1 &> /dev/null

echo '' >> ../$results/all-results
echo '*** SUBDOMAIN TAKEOVER ***' >> ../$results/all-results
echo '' >> ../$results/all-results

if [ -s take1 ]
then
	cat take1 >> ../$results/all-results
fi

for i in $(cat allsubs); do echo http://$i >> take2; done
nuclei -ud /opt/tools/nuclei-templates/ -t takeovers -l take2 -silent | cut -f3,6 -d ' ' >> ../$results/all-results

nuclei -ud /opt/tools/nuclei-templates/ -t dns/azure-takeover-detection.yaml -l allsubs -silent | cut -f3,6 -d ' ' >> ../$results/all-results

### FAVICON RECON ###

echo '[*] Performing favicon recon...'

cat ../$results/live-hosts | favfreak.py | sed -n '/FingerPrint/,/Summary/p' | head -n -4 | tail -n +3 > fav

echo '' >> ../$results/all-results
echo '*** FAVICON RECON ***' >> ../$results/all-results
echo '' >> ../$results/all-results

if [ -s fav ]
then
	cat fav >> ../$results/all-results
fi

### VULN SCAN ###

echo '[*] Running vuln scan...'

echo '' >> ../$results/all-results
echo '*** VULN SCAN ***' >> ../$results/all-results
echo '' >> ../$results/all-results

nuclei -ud /opt/tools/nuclei-templates/ -s critical -t cves,vulnerabilities -l ../$results/live-hosts -silent | cut -f3- -d ' ' >> ../$results/all-results

### EXTRA ###

echo '' >> ../$results/all-results
echo '*** EXTRA ***' >> ../$results/all-results
echo '' >> ../$results/all-results

echo 'Try this Google dork for quick wins:' >> ../$results/all-results
echo '' >> ../$results/all-results
echo "site:$1 ext:config | ext:conf | ext:cnf | ext:cfg | ext:dat | ext:tmp | ext:bak | ext:backup | ext:old | ext:ini | ext:inc | ext:db | ext:sql | ext:sqlite | ext:sqlite3 | ext:mdb | ext:mdf | ext:ora | ext:log | ext:env | ext:pem | ext:kdbx | ext:pst | ext:json | ext:xml" >> ../$results/all-results

### SCREENSHOTS ###

echo '[*] Taking screenshots...'

mkdir ../$results/screenshots
gowitness file -f ../$results/live-hosts -P ../$results/screenshots -D ../$results/screenshots/gowitness.sqlite3 --timeout 5 -t 20 &> /dev/null

### END ###

cd ..
rm -r $temp

echo '[*] Preparing results...'
sleep 3
echo ''
cat $results/all-results

echo ''
echo '[*] Done!'
